### ISSUE TITLE
[Feature] Add FRIENDS & CHAT and ADD A GAME buttons

### ISSUE THREAD

**Issue by beixinti** [SpaceTheme/Steam#10]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature!

First of all, thank you for creating such an amazing Steam theme, Space. I truly enjoy using it, and it has greatly enhanced my Steam experience.

However, I noticed that in the latest version, the Friends & Chat and Add a Game buttons have been removed. These features are very important to me as they significantly improve my user experience.

Therefore, I kindly request that you consider re-adding these buttons in a future update. Thank you very much for your understanding and support!

![h](https://github.com/user-attachments/assets/a14265f5-2fee-4ee7-988f-6242dc597fd5)

**Comment by madmaxgrey** [comment]
a lot is already being done, check out the concepts in the discord server or on the steambrew.app/themes page of what spacetheme will look like, currently on the ko-fi supporter version a lot of this is already done as ko-fi is on version 1.10 alpha

**Comment by SpaceEnergy** [comment]
Nice that you like the theme!

I'll see if I can include an option in the theme settings that the friend button is there, Add game button will be hard to get that under well, but I'll see what I can do in need you can always find it under Games when hovering over the logo

the whole thing will only come in v1.1.1-alpha or later because the userpannel in v1.1.0-alpha is in experimental mode and not ready yet (there is also the download bar in better)

**Comment by beixinti** [comment]
I’m glad to know about the new features in the latest version. Thanks for the hard work!
