### ISSUE TITLE
[Feature] Option to hide the game selector when not on the library page

### ISSUE THREAD

**Issue by Czekoloczek** [SpaceTheme/Steam#34]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature!

I don't really like the feature of having the game selector always shown as it has some bugs like #30 or #33

**Comment by bl4ze1g** [comment]
can confirm this is really annoying, i'm not sure if it's a feature or a bug either as the game selector never shows up on community or when viewing your profile if you never go to the library tab

**Comment by SpaceEnergy** [comment]
#30 had nothing to do with the sidebar (#30 is fixed with v1.1.3-a btw). And there will not be an option to hide the sidebar when you are not in the library, because this is a main feature, later the download bar and all the user buttons will also be in the sidebar:
![image](https://github.com/user-attachments/assets/8c212343-c2f6-44b2-9ee4-c959f1cc6749)
