### ISSUE TITLE
[Feature] Downloads

### ISSUE THREAD

**Issue by Thubbe42** [SpaceTheme/Steam#9]
### Before Requesting

- [X] I found no existing issue matching my feature request

### Describe the feature!

I like minimalism, and this theme does that quite well. But there are some things that I think could be improved.

For starters the Manage Downloads button (island), it takes up a lot of space and while I was testing around with different themes I found one where it was a button at the top. I think this theme would be better if it was just another tab in the middle island called "Downloads"

Something like this has been done in some of the concepts for 18.08 but in my opinion it the variants shown makes the ui a bit more clutered.

Third button from the right in the top right of this image.
![image](https://github.com/user-attachments/assets/c9830a2c-4903-4d0e-b329-04ea6caff2e9)

**Comment by SpaceEnergy** [comment]
so in the update v1.1.0-alpha the download bar is not displayed (you can still see it by hovering over the library text in the navbar), if you have the experimental mode on in v1.1.0-alpha the download bar is only visible when you download something and otherwise it will be hidden
![image](https://github.com/user-attachments/assets/0207e228-015b-46f0-ac78-a63f6692472f)
![image](https://github.com/user-attachments/assets/02e0a35f-a35f-4296-affc-06304ab19820)
But something like an additional tab in the navbar for the download page will probably not come

**Comment by Thubbe42** [comment]
Alright, Thanks for the answer

But for me this brings new questions, specifically the User Panel. Is that something that I can toggle?

I like the simplicity of the 1.0.4 interface but my understanding is that you are aiming for something different.

**Comment by SpaceEnergy** [comment]
So in v1.1.0-alpha it will still be optional in experimental mode but later when I have fixed all the bugs then it will be permanent

But if there are more requests that it should be optional then I will add something

**Comment by Thubbe42** [comment]
Would you be okay if I created a minimalist fork? (not completley sure how I do it but if so I will find out)

**Comment by madmaxgrey** [comment]
> Would you be okay if I created a minimalist fork? (not completley sure how I do it but if so I will find out)

if you know how to theme etc... it would be better to the commuinty entirely for you to make a brand new theme from scratch were looking for new themes, this will also allow you to publish it on millennium, for other users, making a minimal fork of a pre existing theme more than likely won't be accepted since its just a dupe of someone elses

**Comment by SpaceEnergy** [comment]
> Would you be okay if I created a minimalist fork? (not completley sure how I do it but if so I will find out)

sure you can do it but as madmaxgrey already wrote it probably won't make it to the millennium website

**Comment by Thubbe42** [comment]
This should maybe be closed now too, since you pretty much implemented the feature in the last update.
